version: '3.8'

services:
  solr:
    image: solr:latest
    container_name: solr
    hostname: solr
    ports:
      - 8983:8983
    volumes:
      - ./src/main/resources/solr:/opt/solr/server/solr/configsets/scholars-discovery
    command:
      - solr-precreate
      - scholars-discovery
      - /opt/solr/server/solr/configsets/scholars-discovery
