PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>

CONSTRUCT {
  <{{uri}}> rdfs:label ?publicationVenueOutlet .
} WHERE {
  <{{uri}}> a obo:IAO_0000030 .

  OPTIONAL {
  <{{uri}}> vivo:hasPublicationVenue ?publicationVenue .
  ?publicationVenue rdfs:label ?label .
  }

  OPTIONAL {
  <{{uri}}> tamu:publishedProceedings ?publishedProceedings .
  }

  BIND( CONCAT( STR(?label), REPLACE(STR(?publicationVenue), "(^.*/)", "::") ) AS ?labelWithId ) .
  BIND( COALESCE(?labelWithId, ?publishedProceedings) AS ?publicationVenueOutlet)
}
