ui:
  url: http://localhost:4200

middleware:
  ## copy a~n to src/main/resources/assets/a~n
  assets-location: classpath:/assets
  ## works in Windows and expected to work on Linux
  # assets-location: file:/Development/scholars/scholars-discovery/assets
  load-defaults: true
  update-defaults: true
  allowed-origins:
  - ${ui.url}
  - https://login.microsoftonline.com
  auth:
    password:
      duration: 180
      min-length: 8
      max-length: 64
    token:
      server-integer: 1
      server-secret: wKFkxTX54UzKx6xCYnC8WlEI2wtOy0PR
      pseudo-random-number-bytes: 64
    registration-token-duration: 14
    saml2:
      attributeMap:
        firstName: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
        lastName: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
        username: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
  mail:
    from: noreply@library.tamu.edu
    replyTo: helpdesk@library.tamu.edu
  http:
    timeout: 60000
    time-to-live: 60000
    request-timeout: 30000
    socket-timeout: 60000
  index:
    name: scholars-discovery
    cron: 0 0 0 * * SUN
    zone: America/Chicago
    schematize: true
    onStartup: true
    enableIndividualOnBatchFail: true
    onStartupDelay: 10000
    batchSize: 10000
  triplestore:
    type: edu.tamu.scholars.middleware.service.TDBTriplestore
    directory: triplestore
  harvesters:
  - type: edu.tamu.scholars.middleware.discovery.component.jena.TriplestoreHarvester
    documentTypes:
    - edu.tamu.scholars.middleware.discovery.model.Collection
    - edu.tamu.scholars.middleware.discovery.model.Concept
    - edu.tamu.scholars.middleware.discovery.model.Document
    - edu.tamu.scholars.middleware.discovery.model.Organization
    - edu.tamu.scholars.middleware.discovery.model.Person
    - edu.tamu.scholars.middleware.discovery.model.Process
    - edu.tamu.scholars.middleware.discovery.model.Relationship
  indexers:
  - type: edu.tamu.scholars.middleware.discovery.component.solr.SolrIndexer
    documentTypes:
    - edu.tamu.scholars.middleware.discovery.model.Collection
    - edu.tamu.scholars.middleware.discovery.model.Concept
    - edu.tamu.scholars.middleware.discovery.model.Document
    - edu.tamu.scholars.middleware.discovery.model.Organization
    - edu.tamu.scholars.middleware.discovery.model.Person
    - edu.tamu.scholars.middleware.discovery.model.Process
    - edu.tamu.scholars.middleware.discovery.model.Relationship
  export:
    individualKey: individual
    individualBaseUri: ${ui.url}/display

solr:
  host: http://localhost:8983/solr
  client: http1
  default-collection: scholars-discovery
  connection-timeout: 15000
  request-timeout: 120000
  idle-timeout: 120000
  max-connections-per-host: 8
  follow-redirects: true

  cloud:
    zk-hosts:
    - localhost:2181
    - localhost:2182
    - localhost:2183
    zk-chroot: /
    collection-cache-ttl: 60000
    parallel-updates: true
    parallel-cache-refreshes: 8
    retry-expiry-time: 30000
    zk-client-timeout: 15000
    zk-connection-timeout: 10000

  operator: OR
  parser: edismax

vivo:
  email: vivo_root@school.edu
  password:
  base-url: http://localhost:8080/vivo
  linked-open-data-endpoint: /individual
  list-rdf-endpoint: /listrdf
  sparql-query-endpoint: /api/sparqlQuery

logging:
  file:
    name: logs/scholars.log
  level:
    edu:
      tamu:
        scholars:
          middleware: INFO
    org:
      springframework:
        security: INFO
        web: INFO

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  max-http-request-header-size: 16384
  port: 9000
  servlet:
    context-path:
    session:
      cookie:
        # this must match the domain for secure session cookies
        domain: localhost
  tomcat:
    connection-timeout: 900000
  error:
    include-message: always
    include-stacktrace: always

spring:
  security:
    saml2:
      relyingparty:
        registration:
          # TAMU Azure EntraID SAML Enterprise App Registration for localhost.
          entraid:
            entity-id: http://localhost:9000/saml2/service-provider-metadata/entraid
            assertingparty:
              entity-id: https://sts.windows.net/68f381e3-46da-47b9-ba57-6f322b8f0da1/
              metadata-uri: https://login.microsoftonline.com/68f381e3-46da-47b9-ba57-6f322b8f0da1/federationmetadata/2007-06/federationmetadata.xml?appid=2f88008b-4c85-496d-8b96-f5ee076d8dc8
              singlesignon:
                url: https://login.microsoftonline.com/68f381e3-46da-47b9-ba57-6f322b8f0da1/saml2
                sign-request: false
            acs:
              location: http://localhost:9000/login/saml2/sso/entraid
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true
      max-page-size: 10000
    web:
      pageable:
        one-indexed-parameters: true
  liquibase:
    # h2
    # contexts: h2
    # postgres
    contexts: postgres
    enabled: true
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: true
  messages:
    basename: i18n/messages
    cache-duration: 15
    encoding: UTF-8
  h2:
    console:
      enabled: false
      path: /h2console
  datasource:

    # h2
    # driver-class-name: org.h2.Driver
    # h2 in memory
    # url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # h2 file
    # url: jdbc:h2:./h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

    # postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scholars

    username: scholars
    password: scholars
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: false
    show-sql: false
  mail:
    host: smtp-relay.tamu.edu
  profiles:
    active: default
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  sql:
    init:
      # platform: h2
      platform: postgres

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# spring-boot actuator endpoint: health set to true
management:
  endpoints:
    access:
      default: read-only
    web:
      discovery:
        enabled: true
      exposure:
        include: health, info, logfile, openapi, swagger-ui
  endpoint:
    health:
      show-details: always
    info:
      access: read-only
  info:
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

  server:
    port: 9000
    base-path: /actuator

info:
  java-version: ${java.version}
  java-vendor: ${java.vendor}
  environment:
    os:
      name: ${os.name}
